using System.ComponentModel.DataAnnotations;
using ExaminationSystem.Models.Enums;

namespace ExaminationSystem.Models
{
    public class Exam : BaseModel
    {

        [Required]
        [StringLength(100)]
        public string Title { get; set; } = null!;

        public ExamType Type { get; set; }

        public int NumberOfQuestions { get; set; }

        public bool IsAutoGenerated { get; set; }

        public int CourseId { get; set; }
        public Course Course { get; set; } = null!;

        public ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();
        public ICollection<StudentExam> StudentExams { get; set; } = new List<StudentExam>();
    }
} 